version: '3'
services:
  db:
    build: .
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    - ./data:/tmp/data
